# Generated by Django 3.1 on 2020-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('solution', models.CharField(max_length=60)),
                ('answers', models.ManyToManyField(related_name='_question_answers_+', to='cbtapi.Question')),
            ],
        ),
    ]
