# Generated by Django 3.1 on 2020-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0004_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='question',
        ),
        migrations.AddField(
            model_name='result',
            name='isCorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
