# Generated by Django 3.1 on 2020-09-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0005_auto_20200903_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('solution', models.TextField()),
                ('answers', models.TextField()),
            ],
        ),
    ]
