# Generated by Django 3.1 on 2020-09-14 23:11

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0008_auto_20200914_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='options',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=33, null=True, size=3),
        ),
        migrations.AddField(
            model_name='theory',
            name='answer',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=False, max_length=33, size=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theory',
            name='options',
            field=models.CharField(max_length=10),
        ),
    ]
