# Generated by Django 3.1 on 2020-09-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0009_auto_20200914_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theory',
            old_name='options',
            new_name='solution',
        ),
    ]
