# Generated by Django 3.1 on 2020-09-15 18:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0011_auto_20200915_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='options',
            field=django_mysql.models.ListCharField(models.CharField(max_length=30), max_length=124, size=4),
        ),
        migrations.AlterField(
            model_name='objective',
            name='solution',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='answer',
            field=django_mysql.models.ListTextField(models.CharField(max_length=60), size=3),
        ),
        migrations.AlterField(
            model_name='theory',
            name='solution',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
