# Generated by Django 3.1.1 on 2020-09-25 19:19

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0018_auto_20200925_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='answer',
            field=django_mysql.models.ListCharField(models.CharField(max_length=500), max_length=1503, null=True, size=3),
        ),
    ]
