# Generated by Django 3.1.1 on 2020-09-29 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('result', '0011_delete_result_obj'),
        ('cbtapi', '0020_auto_20200925_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
