# Generated by Django 3.1.1 on 2020-09-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtapi', '0021_delete_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='questionId',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
